package contracts.movies

import org.springframework.cloud.contract.spec.Contract

Contract.make {
    description "should create a movie and return it with a generated movie_id for POST /movieservice/v1/movie"
    request {
        method POST()
        urlPath "/movieservice/v1/movie"
        headers {
            contentType applicationJson()
        }
        body(
                name: "Eternals",
                year: 2021,
                cast: "Angelina Jolie, Salma Hayek, Gemma Chan",
                release_date: "2021-10-18"
        )
    }
    response {
        status CREATED()
        headers {
            contentType applicationJson()
        }
        body(
                movie_id: 11,
                name: "Eternals",
                year: 2021,
                cast: "Angelina Jolie, Salma Hayek, Gemma Chan",
                release_date: "2021-10-18"
        )
        bodyMatchers {
            // id is generated by the in-memory sequence — assert it is numeric, not its exact value
            jsonPath('$.movie_id', byRegex(number()))
        }
    }
}
